export const itemsLive = [
  {
    key: 15,
    name: "Live Casino - Mega Roulette",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/mega-roulette-pragmatic.jpg`,
    active: false,
  },
  {
    key: 16,
    name: "Brazilian Roulette",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/brazilian-roulette.png`,
    active: false,
  },
  {
    key: 688,
    name: "Ultimate Roulette",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/ezugi-ultimate-roulette-news-1.jpg`,
    active: false,
  },
  {
    key: 595,
    name: "Blackjack 28 - Azure (Azure Studio II) ",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/bj28.jpg`,
    active: false,
  },
  {
    key: 698,
    name: "Crazy Time",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/crazy_time_thumbnail_winter_branded_1080x1080_10_01+(1).png`,
    active: false,
  },
  {
    key: 6,
    name: "Mega Baccarat",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/MegaBaccarat.jpg`,
    active: false,
  },
  {
    key: 17,
    name: "Dragon Tiger",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/dragon_tiger.jpeg`,
    active: false,
  },
  {
    key: 522,
    name: "Speed Auto Roulette",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/2-6.png`,
    active: false,
  },
  {
    key: 581,
    name: "Blackjack 42 - Ruby",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/bj42.webp`,
    active: false,
  },
  {
    key: 504,
    name: "Live Casino - Sweet Bonanza",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/1-16.jpg`,
    active: false,
  },
  {
    key: 516,
    name: "Roulette 1 Azure ",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/50a38f49-728b-45c9-b0af-318627389367.webp`,
    active: false,
  },
  {
    key: 686,
    name: "Andar Bahar",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/andar_bahar_thumbnail_1080x1080_2023_09.png`,
    active: false,
  },
  {
    key: 562,
    name: "Blackjack 61 - Azure",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/bj61.png`,
    active: false,
  },
  {
    key: 687,
    name: "Casino Hold´em Live",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/evolution-casino-hold-em.jpg`,
    active: false,
  },
  {
    key: 711,
    name: "Fútbol Studio",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/1x1-en.avif`,
    active: false,
  },
  {
    key: 694,
    name: "Dream Catcher",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/dream_catcher_thumbnail_1080x1080_2021_01_03+(1).png`,
    active: false,
  },
  {
    key: 497,
    name: "Live Casino - Mega Wheel ",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/1-7.jpg`,
    active: false,
  },
  {
    key: 18,
    name: "Power Up Roulette",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/powerup-roulette.png`,
    active: false,
  },
  {
    key: 692,
    name: "2 Hand Casino Holdem",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/2-Hand-Casino-Hold_em_thumbnail-400x225.jpg`,
    active: false,
  },
  {
    key: 714,
    name: "Roleta ao Vivo",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/gbQrvFXPvkdoXx.webp`,
    active: false,
  },
  {
    key: 491,
    name: "Live Casino - Roulette",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/roulette-2.webp`,
    active: false,
  },
  {
    key: 701,
    name: "Lightning Roulette",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/lightning_roulette.webp`,
    active: false,
  },
  {
    key: 706,
    name: "Crazy Time A",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/crazy_time_thumbnail_1080x1080_2020_05_01+(1).png`,
    active: false,
  },
  {
    key: 623,
    name: "Speed Baccarat 13",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/sb13.jpg`,
    active: false,
  },
  {
    key: 719,
    name: "Ruleta Relámpago en Vivo",
    href: "/",
    src: `/${process.env.NEXT_PUBLIC_SITE_NAME}/games/live/ruleta-relampago-en-vivo.webp`,
    active: false,
  },
]
